<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXgxtiyz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXgxtiyz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXgxtiyz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXgxtiyz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXgxtiyz\appProdProjectContainer([
    'container.build_hash' => 'Xgxtiyz',
    'container.build_id' => 'db4933d3',
    'container.build_time' => 1577016426,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXgxtiyz');
